-- Seed data generated from data/artists.json + data/shows.json
-- IMPORTANT: publicist_email values below are placeholders derived
-- from the publicist's name. Replace with real login emails before
-- running, or update afterwards with an UPDATE statement.

-- Publicist -> placeholder email map:
--   Becky Kovach -> becky.kovach@bpmpublicity.com

insert into artists (artist_id, name, publicist_name, publicist_email, genre, active) values
  ('311', '311', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('ayodylan', 'Ayodylan', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('babymetal', 'BABYMETAL', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('cartel', 'Cartel', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('catch-your-breath', 'Catch Your Breath', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('dance-gavin-dance', 'Dance Gavin Dance', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('erra', 'Erra', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('good-riddance', 'Good Riddance', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('good-sleepy', 'Good Sleepy', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('harrison-gordon', 'Harrison Gordon', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('hawthorne-heights', 'Hawthorne Heights', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('holywatr', 'Holywatr', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('i-prevail', 'I Prevail', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('if-not-for-me', 'If Not For Me', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('kennyhoopla', 'KennyHoopla', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('lolitslea', 'Lolitslea', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('love-ghost', 'Love Ghost', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('major-league', 'Major League', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('new-found-glory', 'New Found Glory', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('northlane', 'Northlane', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('saosin', 'Saosin', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('silverstein', 'Silverstein', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('state-champs', 'State Champs', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('story-of-the-year', 'Story Of The Year', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('summerbruise', 'Summerbruise', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('super-sometimes', 'Super Sometimes', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('taking-back-sunday', 'Taking Back Sunday', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('thrice', 'Thrice', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('underoath', 'Underoath', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true),
  ('waterparks', 'Waterparks', 'Becky Kovach', 'becky.kovach@bpmpublicity.com', NULL, true)
on conflict (artist_id) do nothing;

insert into shows (artist_id, date, time, venue, city, state_region, country, tour_name, status, ticket_link, notes) values
  ('ayodylan', '2026-09-19', NULL, 'Arlene''s Grocery', 'New York', 'NY', 'USA', 'Energy Drinks For All', 'confirmed', NULL, NULL),
  ('dance-gavin-dance', '2026-09-19', NULL, 'Kentucky State Fair & Exposition Center', 'Louisville', 'KY', 'USA', 'Louder Than Life Festival', 'confirmed', NULL, 'Festival appearance, Saturday lineup'),
  ('erra', '2026-09-19', NULL, 'Newport Music Hall', 'Columbus', 'OH', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-09-19', NULL, 'O2 Academy Leeds', 'Leeds', NULL, 'UK', NULL, 'confirmed', NULL, NULL),
  ('good-riddance', '2026-09-20', NULL, 'Douglass Park', 'Chicago', 'IL', 'USA', 'Riot Fest', 'confirmed', NULL, 'Festival appearance, Sunday lineup'),
  ('i-prevail', '2026-09-20', NULL, 'O2 Academy Glasgow', 'Glasgow', NULL, 'UK', NULL, 'confirmed', NULL, NULL),
  ('babymetal', '2026-09-21', NULL, 'Hollywood Casino Amphitheater', 'Maryland Heights', 'MO', 'USA', 'The Biggest BABYMETAL Tour Ever', 'confirmed', 'https://babymetal.com', 'Support: Halestorm, VIOLENT VIRA'),
  ('erra', '2026-09-21', NULL, 'London Music Hall', 'London', 'ON', 'Canada', NULL, 'confirmed', NULL, NULL),
  ('holywatr', '2026-09-21', NULL, 'Old Rock House', 'St. Louis', 'MO', 'USA', NULL, 'confirmed', NULL, NULL),
  ('ayodylan', '2026-09-22', NULL, 'X-Ray Arcade', 'Cudahy', 'WI', 'USA', 'Energy Drinks For All', 'confirmed', NULL, NULL),
  ('erra', '2026-09-22', NULL, 'Bronson Centre', 'Ottawa', 'ON', 'Canada', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-09-22', NULL, 'O2 Victoria Warehouse', 'Manchester', NULL, 'UK', NULL, 'confirmed', NULL, NULL),
  ('ayodylan', '2026-09-23', NULL, 'Gamma Ray Bar', 'Madison', 'WI', 'USA', 'Energy Drinks For All', 'confirmed', NULL, NULL),
  ('babymetal', '2026-09-23', NULL, 'Dos Equis Pavilion', 'Dallas', 'TX', 'USA', 'The Biggest BABYMETAL Tour Ever', 'confirmed', 'https://babymetal.com', NULL),
  ('holywatr', '2026-09-23', NULL, 'Slowdown', 'Omaha', 'NE', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-09-23', NULL, 'Depot', 'Cardiff', NULL, 'UK', NULL, 'confirmed', NULL, NULL),
  ('taking-back-sunday', '2026-09-23', NULL, 'The Dome at Toyota Oakdale Theatre', 'Wallingford', 'CT', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-09-23', NULL, 'The Dome at Toyota Oakdale Theatre', 'Wallingford', 'CT', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('erra', '2026-09-24', NULL, 'Théâtre Capitole', 'Québec City', 'QC', 'Canada', NULL, 'confirmed', NULL, NULL),
  ('harrison-gordon', '2026-09-24', NULL, 'Brooklyn Bowl', 'Nashville', 'TN', 'USA', 'Mom Jeans Tour', 'confirmed', NULL, 'Support slot'),
  ('holywatr', '2026-09-24', NULL, 'The Bottleneck', 'Lawrence', 'KS', 'USA', NULL, 'confirmed', NULL, NULL),
  ('love-ghost', '2026-09-24', NULL, 'FÜCK OFF ROOM', 'Mexico City', NULL, 'Mexico', NULL, 'confirmed', NULL, NULL),
  ('taking-back-sunday', '2026-09-24', NULL, 'Jones Beach Theater', 'Wantagh', 'NY', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-09-24', NULL, 'Jones Beach Theater', 'Wantagh', 'NY', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('311', '2026-09-25', NULL, 'Elmwood Park Amphitheater', 'Roanoke', 'VA', 'USA', 'Fall 2026', 'confirmed', 'https://311.com/pages/tour', NULL),
  ('babymetal', '2026-09-25', NULL, 'The Cynthia Woods Mitchell Pavilion', 'The Woodlands', 'TX', 'USA', 'The Biggest BABYMETAL Tour Ever', 'confirmed', 'https://babymetal.com', NULL),
  ('i-prevail', '2026-09-25', NULL, 'Alexandra Palace', 'London', NULL, 'UK', NULL, 'confirmed', NULL, NULL),
  ('if-not-for-me', '2026-09-25', NULL, 'Bluebird Theater', 'Denver', 'CO', 'USA', NULL, 'confirmed', NULL, NULL),
  ('love-ghost', '2026-09-25', NULL, 'Hangar Al Rey', 'Guadalajara', NULL, 'Mexico', NULL, 'confirmed', NULL, NULL),
  ('saosin', '2026-09-25', NULL, 'Four Chord Music Festival', 'Pittsburgh', 'PA', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', 'Festival appearance'),
  ('silverstein', '2026-09-25', NULL, 'Huxleys Neue Welt', 'Berlin', NULL, 'Germany', NULL, 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', NULL),
  ('state-champs', '2026-09-25', NULL, 'Four Chord Music Festival', 'Pittsburgh', 'PA', 'USA', NULL, 'confirmed', NULL, 'Festival appearance'),
  ('taking-back-sunday', '2026-09-25', NULL, 'Hard Rock Live at Etess Arena', 'Atlantic City', 'NJ', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-09-25', NULL, 'Hard Rock Live at Etess Arena', 'Atlantic City', 'NJ', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('311', '2026-09-26', NULL, 'Oceans Calling Festival', 'Ocean City', 'MD', 'USA', NULL, 'confirmed', 'https://311.com/pages/tour', 'Festival appearance (Oceans Calling 2026)'),
  ('babymetal', '2026-09-26', NULL, 'Germania Insurance Amphitheater', 'Del Valle', 'TX', 'USA', 'The Biggest BABYMETAL Tour Ever', 'confirmed', 'https://babymetal.com', NULL),
  ('erra', '2026-09-26', NULL, 'Aura', 'Portland', 'ME', 'USA', NULL, 'confirmed', NULL, NULL),
  ('holywatr', '2026-09-26', NULL, 'Fox Theatre', 'Boulder', 'CO', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-09-26', NULL, 'O2 Academy Birmingham', 'Birmingham', NULL, 'UK', NULL, 'confirmed', NULL, NULL),
  ('love-ghost', '2026-09-26', NULL, 'Casa Pädi', 'Pachuca', NULL, 'Mexico', NULL, 'confirmed', NULL, NULL),
  ('major-league', '2026-09-26', NULL, 'Bolero Snort Brewery', 'Carlstadt', 'NJ', 'USA', NULL, 'confirmed', 'https://www.ticketmaster.com/major-league-tickets/artist/1620102', 'Support slot on Four Year Strong show'),
  ('silverstein', '2026-09-26', NULL, 'Zenith, die Kulturhalle', 'Munich', NULL, 'Germany', NULL, 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', NULL),
  ('taking-back-sunday', '2026-09-26', NULL, 'Outdoors at the Palladium', 'Worcester', 'MA', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-09-26', NULL, 'Outdoors at the Palladium', 'Worcester', 'MA', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('erra', '2026-09-27', NULL, 'Empire Live', 'Albany', 'NY', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-09-27', NULL, 'O2 Academy Birmingham', 'Birmingham', NULL, 'UK', NULL, 'confirmed', NULL, 'Second consecutive night'),
  ('taking-back-sunday', '2026-09-27', NULL, 'Brooklyn Paramount', 'Brooklyn', 'NY', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-09-27', NULL, 'Brooklyn Paramount', 'Brooklyn', 'NY', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('holywatr', '2026-09-28', NULL, 'Knitting Factory', 'Boise', 'ID', 'USA', NULL, 'confirmed', NULL, NULL),
  ('babymetal', '2026-09-29', NULL, 'First Financial Credit Union Amphitheater', 'Albuquerque', 'NM', 'USA', 'The Biggest BABYMETAL Tour Ever', 'confirmed', 'https://babymetal.com', NULL),
  ('holywatr', '2026-09-29', NULL, 'District Bar', 'Spokane', 'WA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('taking-back-sunday', '2026-09-29', NULL, 'Outer Harbor Live at Terminal B', 'Buffalo', 'NY', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-09-29', NULL, 'Outer Harbor Live at Terminal B', 'Buffalo', 'NY', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('holywatr', '2026-09-30', NULL, 'WOW Hall', 'Eugene', 'OR', 'USA', NULL, 'confirmed', NULL, NULL),
  ('silverstein', '2026-09-30', NULL, 'Halle 622', 'Zürich', NULL, 'Switzerland', NULL, 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', NULL),
  ('taking-back-sunday', '2026-09-30', NULL, 'GLC Live at 20 Monroe', 'Grand Rapids', 'MI', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-09-30', NULL, 'GLC Live at 20 Monroe', 'Grand Rapids', 'MI', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('babymetal', '2026-10-01', NULL, 'Talking Stick Resort Amphitheatre', 'Phoenix', 'AZ', 'USA', 'The Biggest BABYMETAL Tour Ever', 'confirmed', 'https://babymetal.com', NULL),
  ('good-sleepy', '2026-10-01', NULL, 'Warehouse XI', 'Somerville', 'MA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('harrison-gordon', '2026-10-01', NULL, 'Waiting Room Records', 'Normal', 'IL', 'USA', NULL, 'confirmed', NULL, 'Solo headline show'),
  ('hawthorne-heights', '2026-10-01', NULL, 'Discovery Park', 'Sacramento', 'CA', 'USA', 'Aftershock Festival', 'confirmed', NULL, 'Festival appearance'),
  ('holywatr', '2026-10-01', NULL, 'Discovery Park', 'Sacramento', 'CA', 'USA', 'Aftershock Festival', 'confirmed', NULL, 'Festival appearance, exact set day unconfirmed'),
  ('i-prevail', '2026-10-01', NULL, '013 Poppodium', 'Tilburg', NULL, 'Netherlands', NULL, 'confirmed', NULL, NULL),
  ('new-found-glory', '2026-10-01', NULL, 'Discovery Park', 'Sacramento', 'CA', 'USA', 'Aftershock Festival', 'confirmed', NULL, 'Festival appearance, exact set day unconfirmed'),
  ('summerbruise', '2026-10-01', NULL, 'Healer', 'Indianapolis', 'IN', 'USA', NULL, 'confirmed', NULL, NULL),
  ('if-not-for-me', '2026-10-02', NULL, 'Teragram Ballroom', 'Los Angeles', 'CA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('taking-back-sunday', '2026-10-02', NULL, 'The Rave / Eagles Club', 'Milwaukee', 'WI', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-02', NULL, 'The Rave / Eagles Club', 'Milwaukee', 'WI', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('babymetal', '2026-10-03', NULL, 'Discovery Park (Aftershock Festival)', 'Sacramento', 'CA', 'USA', NULL, 'confirmed', 'https://babymetal.com', 'Festival appearance (Aftershock)'),
  ('i-prevail', '2026-10-03', NULL, 'PSD Bank Dome', 'Düsseldorf', NULL, 'Germany', NULL, 'confirmed', NULL, NULL),
  ('if-not-for-me', '2026-10-03', NULL, 'The Parish, House of Blues', 'Anaheim', 'CA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('saosin', '2026-10-03', NULL, 'Aftershock Festival', 'Sacramento', 'CA', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', 'Festival appearance'),
  ('silverstein', '2026-10-03', NULL, 'O2 Academy Brixton', 'London', NULL, 'UK', NULL, 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', NULL),
  ('taking-back-sunday', '2026-10-03', NULL, 'Val Air Ballroom', 'West Des Moines', 'IA', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-03', NULL, 'Val Air Ballroom', 'West Des Moines', 'IA', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('dance-gavin-dance', '2026-10-04', NULL, 'Discovery Park', 'Sacramento', 'CA', 'USA', 'Aftershock Festival', 'confirmed', NULL, 'Festival appearance'),
  ('if-not-for-me', '2026-10-04', NULL, 'The Rosetta Room', 'Mesa', 'AZ', 'USA', NULL, 'confirmed', NULL, NULL),
  ('taking-back-sunday', '2026-10-04', NULL, 'Midland Theatre', 'Kansas City', 'MO', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-04', NULL, 'Midland Theatre', 'Kansas City', 'MO', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('i-prevail', '2026-10-05', NULL, 'Porsche Arena', 'Stuttgart', NULL, 'Germany', NULL, 'confirmed', NULL, NULL),
  ('silverstein', '2026-10-05', NULL, 'O2 Academy Leeds', 'Leeds', NULL, 'UK', NULL, 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', NULL),
  ('holywatr', '2026-10-06', NULL, 'Walter Studios', 'Phoenix', 'AZ', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-10-06', NULL, 'Zénith Paris La Villette', 'Paris', NULL, 'France', NULL, 'confirmed', NULL, NULL),
  ('silverstein', '2026-10-06', NULL, 'Barrowland Ballroom', 'Glasgow', NULL, 'UK', NULL, 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', NULL),
  ('taking-back-sunday', '2026-10-06', NULL, 'Union Event Center', 'Salt Lake City', 'UT', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-06', NULL, 'Union Event Center', 'Salt Lake City', 'UT', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('if-not-for-me', '2026-10-07', NULL, 'Puzzles Deep Ellum', 'Dallas', 'TX', 'USA', NULL, 'confirmed', NULL, NULL),
  ('holywatr', '2026-10-08', NULL, 'Soundwell', 'Salt Lake City', 'UT', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-10-08', NULL, 'Halle 622', 'Zürich', NULL, 'Switzerland', NULL, 'confirmed', NULL, NULL),
  ('taking-back-sunday', '2026-10-08', NULL, 'Dune Peninsula', 'Tacoma', 'WA', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-08', NULL, 'Dune Peninsula', 'Tacoma', 'WA', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('holywatr', '2026-10-09', NULL, 'Gothic Theatre', 'Englewood', 'CO', 'USA', NULL, 'confirmed', NULL, NULL),
  ('good-riddance', '2026-10-10', NULL, 'Majestic Ventura Theater', 'Ventura', 'CA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-10-10', NULL, 'Halle D, Wiener Stadthalle', 'Vienna', NULL, 'Austria', NULL, 'confirmed', NULL, NULL),
  ('if-not-for-me', '2026-10-10', NULL, 'Bottom Lounge', 'Chicago', 'IL', 'USA', NULL, 'confirmed', NULL, NULL),
  ('taking-back-sunday', '2026-10-10', NULL, 'Frost Amphitheater', 'Stanford', 'CA', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-10', NULL, 'Frost Amphitheater', 'Stanford', 'CA', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('holywatr', '2026-10-11', NULL, 'The Rave / Eagles Club', 'Milwaukee', 'WI', 'USA', NULL, 'confirmed', NULL, NULL),
  ('if-not-for-me', '2026-10-11', NULL, 'St. Andrew''s Hall', 'Detroit', 'MI', 'USA', NULL, 'confirmed', 'https://www.ticketmaster.com/if-not-for-me-tickets/artist/2235713', NULL),
  ('taking-back-sunday', '2026-10-11', NULL, 'Petco Park', 'San Diego', 'CA', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-11', NULL, 'Petco Park', 'San Diego', 'CA', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('holywatr', '2026-10-12', NULL, 'Fine Line', 'Minneapolis', 'MN', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-10-12', NULL, 'Klub Stodoła', 'Warsaw', NULL, 'Poland', NULL, 'confirmed', NULL, NULL),
  ('harrison-gordon', '2026-10-13', NULL, 'The Rino', 'North Kansas City', 'MO', 'USA', NULL, 'confirmed', NULL, 'Solo headline show'),
  ('holywatr', '2026-10-13', NULL, 'Metro', 'Chicago', 'IL', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-10-13', NULL, 'Velodrom', 'Berlin', NULL, 'Germany', NULL, 'confirmed', NULL, NULL),
  ('taking-back-sunday', '2026-10-13', NULL, 'Revel Entertainment Center', 'Albuquerque', 'NM', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-13', NULL, 'Revel Entertainment Center', 'Albuquerque', 'NM', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('taking-back-sunday', '2026-10-14', NULL, 'Red Rocks Amphitheatre', 'Morrison', 'CO', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour; Louder Now 20th anniversary show'),
  ('thrice', '2026-10-14', NULL, 'Red Rocks Amphitheatre', 'Morrison', 'CO', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('hawthorne-heights', '2026-10-15', NULL, 'The Vogue', 'Indianapolis', 'IN', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-10-15', NULL, 'St. Andrew''s Hall', 'Detroit', 'MI', 'USA', 'Deo Gratias Tour', 'confirmed', NULL, NULL),
  ('ayodylan', '2026-10-16', NULL, 'Kona Skate Park', 'Jacksonville', 'FL', 'USA', 'Energy Drinks For All', 'confirmed', 'https://www.bandsintown.com/e/108723056-ayodylan-at-kona-skate-park', 'Final date of tour'),
  ('catch-your-breath', '2026-10-16', NULL, 'Bogart''s', 'Cincinnati', 'OH', 'USA', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-10-16', NULL, 'TBD (Miracle in the Desert)', 'Las Vegas', 'NV', 'USA', NULL, 'confirmed', NULL, 'Two-night engagement Oct 16-17, venue TBD'),
  ('lolitslea', '2026-10-16', NULL, '3 Dots Downtown', 'State College', 'PA', 'USA', NULL, 'confirmed', NULL, 'Final show of current tour run'),
  ('taking-back-sunday', '2026-10-16', NULL, 'Arizona Financial Theatre', 'Phoenix', 'AZ', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-16', NULL, 'Arizona Financial Theatre', 'Phoenix', 'AZ', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('catch-your-breath', '2026-10-17', NULL, 'Vic Theatre', 'Chicago', 'IL', 'USA', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-10-17', NULL, 'TBD (Miracle in the Desert)', 'Las Vegas', 'NV', 'USA', NULL, 'confirmed', NULL, 'Two-night engagement Oct 16-17, venue TBD'),
  ('taking-back-sunday', '2026-10-17', NULL, 'Yaamava'' Theater', 'Highland', 'CA', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-17', NULL, 'Yaamava'' Theater', 'Highland', 'CA', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('catch-your-breath', '2026-10-18', NULL, 'Fillmore Minneapolis', 'Minneapolis', 'MN', 'USA', NULL, 'confirmed', NULL, NULL),
  ('taking-back-sunday', '2026-10-18', NULL, 'Pearl Concert Theater', 'Las Vegas', 'NV', 'USA', 'Fall 2026 Tour with Thrice and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('thrice', '2026-10-18', NULL, 'Pearl Concert Theater', 'Las Vegas', 'NV', 'USA', 'Fall 2026 Tour with Taking Back Sunday and Saves the Day', 'confirmed', NULL, 'Co-headline tour'),
  ('harrison-gordon', '2026-10-19', NULL, 'Treefort Music Hall', 'Boise', 'ID', 'USA', 'Mom Jeans Tour', 'confirmed', NULL, 'Support slot'),
  ('holywatr', '2026-10-19', NULL, 'Newport Music Hall', 'Columbus', 'OH', 'USA', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-10-20', NULL, 'House of Blues', 'Cleveland', 'OH', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, 'With letlive. and Creeper'),
  ('hawthorne-heights', '2026-10-21', NULL, 'Town Ballroom', 'Buffalo', 'NY', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, 'Tour opener'),
  ('holywatr', '2026-10-21', NULL, 'Mod Club Theatre', 'Toronto', 'ON', 'Canada', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-10-22', NULL, 'House of Blues', 'Boston', 'MA', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-10-22', NULL, 'Petit Campus', 'Montreal', 'QC', 'Canada', NULL, 'confirmed', NULL, NULL),
  ('catch-your-breath', '2026-10-23', NULL, 'Summit', 'Denver', 'CO', 'USA', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-10-23', NULL, 'Aura', 'Portland', 'ME', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-10-23', NULL, 'The Song & Dance', 'Syracuse', 'NY', 'USA', NULL, 'confirmed', NULL, NULL),
  ('saosin', '2026-10-23', NULL, 'House of Blues', 'Anaheim', 'CA', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', 'Tour opener'),
  ('summerbruise', '2026-10-23', NULL, 'FEST', 'Gainesville', 'FL', 'USA', 'The Fest 2026', 'confirmed', NULL, 'Festival appearance'),
  ('catch-your-breath', '2026-10-24', NULL, 'The Depot', 'Salt Lake City', 'UT', 'USA', NULL, 'confirmed', NULL, NULL),
  ('harrison-gordon', '2026-10-24', NULL, 'AM/FM', 'Dallas', 'TX', 'USA', 'Mom Jeans Tour', 'confirmed', NULL, 'Support slot'),
  ('hawthorne-heights', '2026-10-24', NULL, 'Irving Plaza', 'New York', 'NY', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-10-24', NULL, 'The Marquee', 'Tempe', 'AZ', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('harrison-gordon', '2026-10-25', NULL, 'Emo''s Austin', 'Austin', 'TX', 'USA', 'Mom Jeans Tour', 'confirmed', NULL, 'Support slot'),
  ('hawthorne-heights', '2026-10-25', NULL, 'Starland Ballroom', 'Sayreville', 'NJ', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-10-25', NULL, 'Paradise Rock Club', 'Boston', 'MA', 'USA', 'Deo Gratias Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-10-25', NULL, 'Sunshine Theater', 'Albuquerque', 'NM', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('harrison-gordon', '2026-10-27', NULL, 'Rialto Theatre', 'Tucson', 'AZ', 'USA', 'Mom Jeans Tour', 'confirmed', NULL, 'Support slot'),
  ('holywatr', '2026-10-27', NULL, 'Empire Underground', 'Albany', 'NY', 'USA', 'Deo Gratias Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-10-27', NULL, 'Vibes Event Center', 'San Antonio', 'TX', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('waterparks', '2026-10-27', NULL, 'Soundwell', 'Salt Lake City', 'UT', 'USA', NULL, 'confirmed', NULL, NULL),
  ('harrison-gordon', '2026-10-28', NULL, 'Riverside Municipal Auditorium', 'Riverside', 'CA', 'USA', 'Mom Jeans Tour', 'confirmed', NULL, 'Support slot'),
  ('hawthorne-heights', '2026-10-28', NULL, 'XL Live', 'Harrisburg', 'PA', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-10-28', NULL, 'House of Blues', 'Dallas', 'TX', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('hawthorne-heights', '2026-10-29', NULL, 'Baltimore Soundstage', 'Baltimore', 'MD', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-10-29', NULL, 'House of Blues', 'Houston', 'TX', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('waterparks', '2026-10-29', NULL, 'Oriental Theater', 'Denver', 'CO', 'USA', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-10-30', NULL, 'Elevation 27', 'Virginia Beach', 'VA', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-10-30', NULL, 'First Unitarian Church', 'Philadelphia', 'PA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('saosin', '2026-10-30', NULL, 'House of Blues', 'New Orleans', 'LA', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('catch-your-breath', '2026-10-31', NULL, 'The Observatory', 'Santa Ana', 'CA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-10-31', NULL, 'The Underground', 'Charlotte', 'NC', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-10-31', NULL, '9:30 Club', 'Washington', 'DC', 'USA', 'Deo Gratias Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-10-31', NULL, 'Vinyl Music Hall', 'Pensacola', 'FL', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('thrice', '2026-10-31', NULL, 'Hollywood Bowl', 'Hollywood', 'CA', 'USA', NULL, 'confirmed', NULL, 'Special guest with My Chemical Romance'),
  ('waterparks', '2026-10-31', NULL, 'Granada Theatre', 'Lawrence', 'KS', 'USA', NULL, 'confirmed', NULL, NULL),
  ('harrison-gordon', '2026-11-01', NULL, 'Channel 24', 'Sacramento', 'CA', 'USA', 'Mom Jeans Tour', 'confirmed', NULL, 'Support slot'),
  ('hawthorne-heights', '2026-11-01', NULL, 'Charleston Music Hall', 'Charleston', 'SC', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('i-prevail', '2026-11-01', NULL, 'Bridgestone Arena', 'Nashville', 'TN', 'USA', 'Alienation Tour', 'confirmed', NULL, 'Supporting Three Days Grace'),
  ('saosin', '2026-11-01', NULL, 'House of Blues', 'Orlando', 'FL', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('erra', '2026-11-02', NULL, 'TivoliVredenburg', 'Utrecht', NULL, 'Netherlands', NULL, 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-02', NULL, 'Irving Plaza', 'New York', 'NY', 'USA', 'Deo Gratias Tour', 'confirmed', NULL, NULL),
  ('waterparks', '2026-11-02', NULL, 'Varsity Theater', 'Minneapolis', 'MN', 'USA', NULL, 'confirmed', NULL, NULL),
  ('harrison-gordon', '2026-11-03', NULL, 'Grey Witch', 'Henderson', 'NV', 'USA', NULL, 'confirmed', NULL, 'Solo headline show'),
  ('hawthorne-heights', '2026-11-03', NULL, 'The Orange Peel', 'Asheville', 'NC', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-03', NULL, 'Elevation 27', 'Virginia Beach', 'VA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-11-03', NULL, 'Peoria Civic Center', 'Peoria', 'IL', 'USA', 'Alienation Tour', 'confirmed', NULL, 'Supporting Three Days Grace'),
  ('saosin', '2026-11-03', NULL, 'Brooklyn Bowl', 'Nashville', 'TN', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('erra', '2026-11-04', NULL, 'Grosse Freiheit 36', 'Hamburg', NULL, 'Germany', NULL, 'confirmed', NULL, NULL),
  ('harrison-gordon', '2026-11-04', NULL, 'Revel Entertainment Center', 'Albuquerque', 'NM', 'USA', NULL, 'confirmed', NULL, 'Solo headline show'),
  ('hawthorne-heights', '2026-11-04', NULL, 'Mercury Ballroom', 'Louisville', 'KY', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-04', NULL, 'Capone''s', 'Johnson City', 'TN', 'USA', NULL, 'confirmed', NULL, NULL),
  ('i-prevail', '2026-11-04', NULL, 'Gainbridge Fieldhouse', 'Indianapolis', 'IN', 'USA', 'Alienation Tour', 'confirmed', NULL, 'Supporting Three Days Grace'),
  ('saosin', '2026-11-04', NULL, 'The Ritz', 'Raleigh', 'NC', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('waterparks', '2026-11-04', NULL, 'The Rave / Eagles Club', 'Milwaukee', 'WI', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('311', '2026-11-05', NULL, 'Arizona Financial Theatre', 'Phoenix', 'AZ', 'USA', 'Fall 2026', 'confirmed', 'https://311.com/pages/tour', NULL),
  ('cartel', '2026-11-05', NULL, 'Archer Music Hall', 'Allentown', 'PA', 'USA', 'State Champs Tour', 'confirmed', NULL, 'Support slot for State Champs'),
  ('erra', '2026-11-05', NULL, 'Felsenkeller', 'Leipzig', NULL, 'Germany', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-05', NULL, 'Cannery Hall', 'Nashville', 'TN', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('northlane', '2026-11-05', NULL, 'Metro City', 'Perth', 'WA', 'Australia', 'The Anemoia Experience', 'confirmed', NULL, NULL),
  ('state-champs', '2026-11-05', NULL, 'Archer Music Hall', 'Allentown', 'PA', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/state-champs-tickets/artist/1637436', NULL),
  ('underoath', '2026-11-05', NULL, 'The Pageant', 'St. Louis', 'MO', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-05', NULL, 'The Rave / Eagles Club', 'Milwaukee', 'WI', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('311', '2026-11-06', NULL, 'SEMA Fest 2026', 'Las Vegas', 'NV', 'USA', NULL, 'confirmed', 'https://311.com/pages/tour', 'Festival appearance'),
  ('cartel', '2026-11-06', NULL, 'Buffalo RiverWorks', 'Buffalo', 'NY', 'USA', 'State Champs Tour', 'confirmed', NULL, 'Support slot for State Champs'),
  ('erra', '2026-11-06', NULL, 'Carlswerk Victoria', 'Cologne', NULL, 'Germany', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-06', NULL, 'The Masquerade', 'Atlanta', 'GA', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-06', NULL, 'The Pyrle', 'Greensboro', 'NC', 'USA', NULL, 'confirmed', NULL, NULL),
  ('saosin', '2026-11-06', NULL, 'Starland Ballroom', 'Sayreville', 'NJ', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('state-champs', '2026-11-06', NULL, 'Buffalo RiverWorks', 'Buffalo', 'NY', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('underoath', '2026-11-06', NULL, 'The Criterion', 'Oklahoma City', 'OK', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-06', NULL, 'The Rave / Eagles Club', 'Milwaukee', 'WI', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('cartel', '2026-11-07', NULL, 'Old National Centre', 'Indianapolis', 'IN', 'USA', 'State Champs Tour', 'confirmed', NULL, 'Support slot for State Champs'),
  ('dance-gavin-dance', '2026-11-07', NULL, 'The Tivoli', 'Brisbane', 'QLD', 'Australia', NULL, 'confirmed', NULL, NULL),
  ('erra', '2026-11-07', NULL, 'Den Atelier', 'Luxembourg City', NULL, 'Luxembourg', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-07', NULL, 'Iron City', 'Birmingham', 'AL', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-07', NULL, 'Music Farm', 'Charleston', 'SC', 'USA', NULL, 'confirmed', NULL, NULL),
  ('northlane', '2026-11-07', NULL, 'Festival Hall Melbourne', 'West Melbourne', 'VIC', 'Australia', 'The Anemoia Experience', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-07', NULL, 'Webster Hall', 'New York', 'NY', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('state-champs', '2026-11-07', NULL, 'Old National Centre', 'Indianapolis', 'IN', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('underoath', '2026-11-07', NULL, 'Revel Entertainment Center', 'Albuquerque', 'NM', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('311', '2026-11-08', NULL, 'Mission Ballroom', 'Denver', 'CO', 'USA', 'Fall 2026', 'confirmed', 'https://311.com/pages/tour', NULL),
  ('cartel', '2026-11-08', NULL, 'The Pageant', 'St. Louis', 'MO', 'USA', 'State Champs Tour', 'confirmed', NULL, 'Support slot for State Champs'),
  ('catch-your-breath', '2026-11-08', NULL, 'Tabernacle', 'Atlanta', 'GA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('dance-gavin-dance', '2026-11-08', NULL, 'Enmore Theatre', 'Newtown', 'NSW', 'Australia', NULL, 'confirmed', NULL, NULL),
  ('harrison-gordon', '2026-11-08', NULL, 'Blueberry Hill Duck Room', 'St. Louis', 'MO', 'USA', NULL, 'confirmed', NULL, 'Solo headline show'),
  ('hawthorne-heights', '2026-11-08', NULL, 'House of Blues', 'New Orleans', 'LA', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-08', NULL, 'The Masquerade - Heaven', 'Atlanta', 'GA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('northlane', '2026-11-08', NULL, 'Thebarton Theatre', 'Torrensville', 'SA', 'Australia', 'The Anemoia Experience', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-08', NULL, 'The Palladium', 'Worcester', 'MA', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('state-champs', '2026-11-08', NULL, 'The Pageant', 'St. Louis', 'MO', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('waterparks', '2026-11-08', NULL, 'The Roxy', 'Lakewood', 'OH', 'USA', NULL, 'confirmed', NULL, NULL),
  ('underoath', '2026-11-09', NULL, 'Arizona Financial Theatre', 'Phoenix', 'AZ', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('dance-gavin-dance', '2026-11-10', NULL, 'The Gov', 'Hindmarsh', 'SA', 'Australia', NULL, 'confirmed', NULL, NULL),
  ('erra', '2026-11-10', NULL, 'Galvanizers Yard, SWG3', 'Glasgow', NULL, 'UK', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-10', NULL, 'Vinyl Music Hall', 'Pensacola', 'FL', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-10', NULL, 'Saturn', 'Birmingham', 'AL', 'USA', NULL, 'confirmed', NULL, NULL),
  ('saosin', '2026-11-10', NULL, 'Brooklyn Bowl', 'Philadelphia', 'PA', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('state-champs', '2026-11-10', NULL, 'Echo Lounge & Music Hall', 'Dallas', 'TX', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('underoath', '2026-11-10', NULL, 'SOMA', 'San Diego', 'CA', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-10', NULL, 'Toad''s Place', 'New Haven', 'CT', 'USA', NULL, 'confirmed', NULL, NULL),
  ('311', '2026-11-11', NULL, 'The Factory', 'Chesterfield', 'MO', 'USA', 'Fall 2026', 'confirmed', 'https://311.com/pages/tour', NULL),
  ('northlane', '2026-11-11', NULL, 'Enmore Theatre', 'Newtown', 'NSW', 'Australia', 'The Anemoia Experience', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-11', NULL, 'Nevermore Hall', 'Baltimore', 'MD', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('cartel', '2026-11-12', NULL, 'The Van Buren', 'Phoenix', 'AZ', 'USA', 'State Champs Tour', 'confirmed', NULL, 'Support slot for State Champs'),
  ('dance-gavin-dance', '2026-11-12', NULL, 'Freo.Social', 'Fremantle', 'WA', 'Australia', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-12', NULL, 'Jannus Live', 'St. Petersburg', 'FL', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-12', NULL, 'The Wooly', 'Gainesville', 'FL', 'USA', NULL, 'confirmed', NULL, NULL),
  ('state-champs', '2026-11-12', NULL, 'The Van Buren', 'Phoenix', 'AZ', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('underoath', '2026-11-12', NULL, 'Brooklyn Bowl', 'Las Vegas', 'NV', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-12', NULL, 'House of Independents', 'Asbury Park', 'NJ', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('311', '2026-11-13', NULL, 'Greater Jacksonville Agricultural Fair', 'Jacksonville', 'FL', 'USA', NULL, 'confirmed', 'https://311.com/pages/tour', 'Fair appearance'),
  ('catch-your-breath', '2026-11-13', NULL, 'Irving Plaza', 'New York', 'NY', 'USA', NULL, 'confirmed', NULL, NULL),
  ('erra', '2026-11-13', NULL, 'Leeds University Stylus', 'Leeds', NULL, 'UK', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-13', NULL, 'Revolution Live', 'Fort Lauderdale', 'FL', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-13', NULL, 'Zodiac', 'Tampa', 'FL', 'USA', NULL, 'confirmed', NULL, NULL),
  ('northlane', '2026-11-13', NULL, 'Bar on the Hill, Newcastle University', 'Newcastle', 'NSW', 'Australia', 'The Anemoia Experience', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-13', NULL, 'Town Ballroom', 'Buffalo', 'NY', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('state-champs', '2026-11-13', NULL, 'Brooklyn Bowl', 'Las Vegas', 'NV', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('underoath', '2026-11-13', NULL, 'Hollywood Palladium', 'Los Angeles', 'CA', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-13', NULL, 'House of Independents', 'Asbury Park', 'NJ', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('311', '2026-11-14', NULL, 'Vans Warped Tour Orlando', 'Orlando', 'FL', 'USA', NULL, 'confirmed', 'https://311.com/pages/tour', 'Festival appearance (Vans Warped Tour)'),
  ('cartel', '2026-11-14', NULL, 'Vans Warped Tour Orlando', 'Orlando', 'FL', 'USA', NULL, 'confirmed', NULL, 'Festival appearance (Vans Warped Tour)'),
  ('dance-gavin-dance', '2026-11-14', NULL, 'Vans Warped Tour Orlando', 'Orlando', 'FL', 'USA', NULL, 'confirmed', NULL, 'Festival appearance, exact set day unconfirmed'),
  ('hawthorne-heights', '2026-11-14', NULL, 'Vans Warped Tour Orlando', 'Orlando', 'FL', 'USA', NULL, 'confirmed', NULL, 'Festival appearance, exact set day unconfirmed'),
  ('holywatr', '2026-11-14', NULL, 'Vans Warped Tour Orlando', 'Orlando', 'FL', 'USA', NULL, 'confirmed', NULL, 'Festival appearance'),
  ('i-prevail', '2026-11-14', NULL, 'Ford Idaho Center Arena', 'Boise', 'ID', 'USA', 'Alienation Tour', 'confirmed', NULL, 'Supporting Three Days Grace'),
  ('kennyhoopla', '2026-11-14', NULL, 'Vans Warped Tour Orlando', 'Orlando', 'FL', 'USA', NULL, 'confirmed', 'https://www.ticketmaster.com/kennyhoopla-tickets/artist/2540462', 'Festival appearance'),
  ('new-found-glory', '2026-11-14', NULL, 'Vans Warped Tour Orlando', 'Orlando', 'FL', 'USA', NULL, 'confirmed', 'https://www.ticketmaster.com/new-found-glory-tickets/artist/712420', 'Festival appearance'),
  ('northlane', '2026-11-14', NULL, 'Fortitude Music Hall', 'Brisbane', 'QLD', 'Australia', 'The Anemoia Experience', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-14', NULL, 'The Majestic', 'Detroit', 'MI', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('state-champs', '2026-11-14', NULL, 'Riverside Municipal Auditorium', 'Riverside', 'CA', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('super-sometimes', '2026-11-14', NULL, 'Vans Warped Tour Orlando', 'Orlando', 'FL', 'USA', NULL, 'confirmed', NULL, 'Festival appearance'),
  ('thrice', '2026-11-14', NULL, 'Vans Warped Tour Orlando', 'Orlando', 'FL', 'USA', NULL, 'confirmed', NULL, 'Festival appearance'),
  ('underoath', '2026-11-14', NULL, 'The Masonic', 'San Francisco', 'CA', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-14', NULL, 'House of Independents', 'Asbury Park', 'NJ', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('saosin', '2026-11-15', NULL, 'House of Blues', 'Chicago', 'IL', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('state-champs', '2026-11-15', NULL, 'Ace of Spades', 'Sacramento', 'CA', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('silverstein', '2026-11-16', NULL, 'Showbox SoDo', 'Seattle', 'WA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('story-of-the-year', '2026-11-16', NULL, 'Showbox SoDo', 'Seattle', 'WA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-11-16', NULL, 'Paramount Theatre', 'Seattle', 'WA', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-16', NULL, 'The Recher', 'Towson', 'MD', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('hawthorne-heights', '2026-11-17', NULL, 'The Vogue', 'Indianapolis', 'IN', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-17', NULL, 'White Oak Music Hall', 'Houston', 'TX', 'USA', 'Deo Gratias Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-17', NULL, 'The Rave II', 'Milwaukee', 'WI', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('silverstein', '2026-11-17', NULL, 'Knitting Factory', 'Spokane', 'WA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-11-17', NULL, 'Roseland Theater', 'Portland', 'OR', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-11-17', NULL, 'Knitting Factory', 'Spokane', 'WA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-11-17', NULL, 'PNE Forum', 'Vancouver', 'BC', 'Canada', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-17', NULL, 'The Recher', 'Towson', 'MD', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('erra', '2026-11-18', NULL, 'Z7 Konzertfabrik', 'Pratteln', NULL, 'Switzerland', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-18', NULL, 'House of Blues', 'Chicago', 'IL', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-18', NULL, 'Scoot Inn', 'Austin', 'TX', 'USA', NULL, 'confirmed', NULL, NULL),
  ('saosin', '2026-11-18', NULL, 'The Fillmore', 'Minneapolis', 'MN', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('silverstein', '2026-11-18', NULL, 'Crystal Ballroom', 'Portland', 'OR', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-11-18', NULL, 'The Showbox', 'Seattle', 'WA', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-11-18', NULL, 'McMenamins Crystal Ballroom', 'Portland', 'OR', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('catch-your-breath', '2026-11-19', NULL, 'Danforth Music Hall', 'Toronto', 'ON', 'Canada', NULL, 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-19', NULL, 'Echo Lounge & Music Hall', 'Dallas', 'TX', 'USA', NULL, 'confirmed', NULL, NULL),
  ('silverstein', '2026-11-19', NULL, 'Hard Rock Live Sacramento', 'Wheatland', 'CA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('story-of-the-year', '2026-11-19', NULL, 'Hard Rock Live Sacramento', 'Wheatland', 'CA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-11-19', NULL, 'Union Event Center', 'Salt Lake City', 'UT', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('hawthorne-heights', '2026-11-20', NULL, 'Clyde Theatre', 'Fort Wayne', 'IN', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-20', NULL, 'Summit Music Hall', 'Denver', 'CO', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('state-champs', '2026-11-20', NULL, 'The Complex', 'Salt Lake City', 'UT', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('waterparks', '2026-11-20', NULL, 'The Masquerade - Hell', 'Atlanta', 'GA', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('hawthorne-heights', '2026-11-21', NULL, 'Elevation, The Intersection', 'Grand Rapids', 'MI', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-21', NULL, 'The Complex', 'Salt Lake City', 'UT', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('silverstein', '2026-11-21', NULL, 'Riverside Municipal Auditorium', 'Riverside', 'CA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-11-21', NULL, 'Summit', 'Denver', 'CO', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-11-21', NULL, 'Riverside Municipal Auditorium', 'Riverside', 'CA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('super-sometimes', '2026-11-21', NULL, 'SilverLakes', 'Norco', 'CA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('underoath', '2026-11-21', NULL, 'Fillmore Auditorium', 'Denver', 'CO', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-21', NULL, 'The Masquerade - Hell', 'Atlanta', 'GA', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('erra', '2026-11-22', NULL, 'Raiffeisen Halle im Gasometer', 'Vienna', NULL, 'Austria', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-22', NULL, 'St. Andrew''s Hall', 'Detroit', 'MI', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('holywatr', '2026-11-22', NULL, 'The Fonda Theatre', 'Los Angeles', 'CA', 'USA', NULL, 'confirmed', 'https://www.ticketmaster.com/holywatr-tickets/artist/3452574', NULL),
  ('i-prevail', '2026-11-22', NULL, 'Intuit Dome', 'Inglewood', 'CA', 'USA', 'Alienation Tour', 'confirmed', 'https://www.ticketmaster.com/i-prevail-tickets/artist/2084435', 'Supporting Three Days Grace; tour finale'),
  ('saosin', '2026-11-22', NULL, 'Knitting Factory', 'Boise', 'ID', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('silverstein', '2026-11-22', NULL, 'The Wiltern', 'Los Angeles', 'CA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('story-of-the-year', '2026-11-22', NULL, 'The Wiltern', 'Los Angeles', 'CA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('super-sometimes', '2026-11-22', NULL, 'August Hall', 'San Francisco', 'CA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('waterparks', '2026-11-22', NULL, 'The Masquerade - Hell', 'Atlanta', 'GA', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('erra', '2026-11-23', NULL, 'Muffathalle', 'Munich', NULL, 'Germany', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-23', NULL, 'Warehouse on Broadway', 'Kansas City', 'MO', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('state-champs', '2026-11-23', NULL, 'Capitol Theatre', 'Davenport', 'IA', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('underoath', '2026-11-23', NULL, 'The Armory', 'Minneapolis', 'MN', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('erra', '2026-11-24', NULL, 'ASTRA Kulturhaus', 'Berlin', NULL, 'Germany', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-24', NULL, 'The Vanguard', 'Tulsa', 'OK', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-24', NULL, 'Showbox SoDo', 'Seattle', 'WA', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('silverstein', '2026-11-24', NULL, 'Sunshine Theater', 'Albuquerque', 'NM', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-11-24', NULL, 'Mercury Ballroom', 'Louisville', 'KY', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-11-24', NULL, 'Sunshine Theater', 'Albuquerque', 'NM', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-11-24', NULL, 'Aragon Ballroom', 'Chicago', 'IL', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-24', NULL, 'House of Blues Orlando', 'Lake Buena Vista', 'FL', 'USA', NULL, 'confirmed', NULL, NULL),
  ('hawthorne-heights', '2026-11-25', NULL, 'The Hawthorn', 'St. Louis', 'MO', 'USA', 'If Only You Were Lonely 20th Anniversary Tour', 'confirmed', NULL, NULL),
  ('saosin', '2026-11-25', NULL, 'Roseland Theater', 'Portland', 'OR', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('silverstein', '2026-11-25', NULL, 'The Criterion', 'Oklahoma City', 'OK', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-11-25', NULL, 'Newport Music Hall', 'Columbus', 'OH', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-11-25', NULL, 'The Criterion', 'Oklahoma City', 'OK', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-11-25', NULL, 'GLC Live at 20 Monroe', 'Grand Rapids', 'MI', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('kennyhoopla', '2026-11-27', NULL, 'Bogart''s', 'Cincinnati', 'OH', 'USA', NULL, 'confirmed', NULL, 'Jack Kays'' 3rd Annual "Jack''s Jam" event'),
  ('saosin', '2026-11-27', NULL, 'The Novo', 'Los Angeles', 'CA', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', NULL),
  ('state-champs', '2026-11-27', NULL, 'Starland Ballroom', 'Sayreville', 'NJ', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('underoath', '2026-11-27', NULL, 'Great Canadian Toronto', 'Toronto', 'ON', 'Canada', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('babymetal', '2026-11-28', NULL, 'Espaco Unimed', 'Sao Paulo', NULL, 'Brazil', 'The Biggest BABYMETAL Tour Ever', 'confirmed', 'https://babymetal.com', NULL),
  ('northlane', '2026-11-28', NULL, 'KK''s Steel Mill', 'Wolverhampton', NULL, 'UK', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('saosin', '2026-11-28', NULL, 'SOMA', 'San Diego', 'CA', 'USA', 'Self-Titled 20th Anniversary Tour', 'confirmed', 'https://www.ticketmaster.com/saosin-tickets/artist/982712', 'Tour closer'),
  ('silverstein', '2026-11-28', NULL, 'The Tabernacle', 'Atlanta', 'GA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-11-28', NULL, 'Palladium', 'Worcester', 'MA', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-11-28', NULL, 'Tabernacle', 'Atlanta', 'GA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('super-sometimes', '2026-11-28', NULL, 'The Federal Theatre', 'Denver', 'CO', 'USA', NULL, 'confirmed', NULL, NULL),
  ('underoath', '2026-11-28', NULL, 'MTELUS', 'Montreal', 'QC', 'Canada', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-28', NULL, 'Scout Bar', 'Houston', 'TX', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('northlane', '2026-11-29', NULL, 'KK''s Steel Mill', 'Wolverhampton', NULL, 'UK', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('silverstein', '2026-11-29', NULL, 'Jannus Live', 'St. Petersburg', 'FL', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-11-29', NULL, 'Nevermore Hall', 'Baltimore', 'MD', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-11-29', NULL, 'Jannus Live', 'St. Petersburg', 'FL', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-11-29', NULL, 'MGM Music Hall at Fenway', 'Boston', 'MA', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-11-29', NULL, 'Scout Bar', 'Houston', 'TX', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('babymetal', '2026-12-01', NULL, 'Movistar Arena', 'Buenos Aires', NULL, 'Argentina', 'The Biggest BABYMETAL Tour Ever', 'confirmed', 'https://babymetal.com', NULL),
  ('northlane', '2026-12-01', NULL, 'Project House', 'Leeds', NULL, 'UK', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('silverstein', '2026-12-01', NULL, 'The Ritz', 'Raleigh', 'NC', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-12-01', NULL, 'The National', 'Richmond', 'VA', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-12-01', NULL, 'The Ritz', 'Raleigh', 'NC', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-12-01', NULL, 'The Fillmore Philadelphia', 'Philadelphia', 'PA', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('northlane', '2026-12-02', NULL, 'Manchester Academy 1', 'Manchester', NULL, 'UK', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('silverstein', '2026-12-02', NULL, 'Nevermore Hall', 'Baltimore', 'MD', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('story-of-the-year', '2026-12-02', NULL, 'Nevermore Hall', 'Baltimore', 'MD', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('waterparks', '2026-12-02', NULL, 'La Rosa', 'Tucson', 'AZ', 'USA', NULL, 'confirmed', NULL, NULL),
  ('babymetal', '2026-12-03', NULL, 'Movistar Arena', 'Santiago', NULL, 'Chile', 'The Biggest BABYMETAL Tour Ever', 'confirmed', 'https://babymetal.com', NULL),
  ('northlane', '2026-12-03', NULL, 'The Prospect Building', 'Bristol', NULL, 'UK', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('state-champs', '2026-12-03', NULL, 'Brooklyn Bowl', 'Nashville', 'TN', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('underoath', '2026-12-03', NULL, 'Freedom Hall', 'Lancaster', 'PA', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('silverstein', '2026-12-04', NULL, 'The Fillmore', 'Philadelphia', 'PA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-12-04', NULL, 'Tabernacle', 'Atlanta', 'GA', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-12-04', NULL, 'The Fillmore Philadelphia', 'Philadelphia', 'PA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-12-04', NULL, 'Andrew J. Brady Music Center', 'Cincinnati', 'OH', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-12-04', NULL, 'The Observatory', 'Santa Ana', 'CA', 'USA', NULL, 'confirmed', NULL, NULL),
  ('cartel', '2026-12-05', NULL, 'Jannus Live', 'St. Petersburg', 'FL', 'USA', 'State Champs Tour', 'confirmed', NULL, 'Support slot for State Champs'),
  ('northlane', '2026-12-05', NULL, 'O2 Academy Glasgow', 'Glasgow', NULL, 'UK', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('silverstein', '2026-12-05', NULL, 'Agora Theatre', 'Cleveland', 'OH', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('state-champs', '2026-12-05', NULL, 'Jannus Live', 'St. Petersburg', 'FL', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-12-05', NULL, 'Agora Theatre', 'Cleveland', 'OH', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-12-05', NULL, 'Egyptian Room at Old National Centre', 'Indianapolis', 'IN', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('northlane', '2026-12-06', NULL, 'O2 Academy Brixton', 'London', NULL, 'UK', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('state-champs', '2026-12-06', NULL, 'House of Blues Orlando', 'Lake Buena Vista', 'FL', 'USA', 'Around The World And Back Again 10th Anniversary Tour', 'confirmed', NULL, NULL),
  ('story-of-the-year', '2026-12-06', NULL, 'Riviera Theatre', 'Chicago', 'IL', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-12-06', NULL, 'The Fillmore Detroit', 'Detroit', 'MI', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('waterparks', '2026-12-06', NULL, 'Ace of Spades', 'Sacramento', 'CA', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('waterparks', '2026-12-07', NULL, 'Ace of Spades', 'Sacramento', 'CA', 'USA', NULL, 'confirmed', NULL, 'Multi-night run'),
  ('northlane', '2026-12-08', NULL, 'Élysée Montmartre', 'Paris', NULL, 'France', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('silverstein', '2026-12-08', NULL, 'The Rave', 'Milwaukee', 'WI', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('story-of-the-year', '2026-12-08', NULL, 'The Rave / Eagles Club', 'Milwaukee', 'WI', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-12-08', NULL, 'Brooklyn Paramount', 'Brooklyn', 'NY', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('northlane', '2026-12-09', NULL, 'Turbinenhalle 1', 'Oberhausen', NULL, 'Germany', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('silverstein', '2026-12-09', NULL, 'Royal Oak Music Theatre', 'Royal Oak', 'MI', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('story-of-the-year', '2026-12-09', NULL, 'Royal Oak Music Theatre', 'Royal Oak', 'MI', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('northlane', '2026-12-10', NULL, 'Capitol', 'Hannover', NULL, 'Germany', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('silverstein', '2026-12-11', NULL, 'Stage AE', 'Pittsburgh', 'PA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('story-of-the-year', '2026-12-11', NULL, 'Stage AE', 'Pittsburgh', 'PA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-12-11', NULL, 'The Ritz', 'Raleigh', 'NC', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('i-prevail', '2026-12-12', NULL, 'Estadio Fray Nano de Beisbol', 'Mexico City', NULL, 'Mexico', NULL, 'confirmed', NULL, 'BABYMETAL festival appearance'),
  ('northlane', '2026-12-12', NULL, 'Klub Proxima', 'Warsaw', NULL, 'Poland', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('silverstein', '2026-12-12', NULL, 'Palladium Times Square', 'New York', 'NY', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year'),
  ('story-of-the-year', '2026-12-12', NULL, 'Palladium Times Square', 'New York', 'NY', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-12-12', NULL, 'House of Blues', 'North Myrtle Beach', 'SC', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('northlane', '2026-12-13', NULL, 'Huxleys Neue Welt', 'Berlin', NULL, 'Germany', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('silverstein', '2026-12-13', NULL, 'Citizens House of Blues Boston', 'Boston', 'MA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', 'https://www.ticketmaster.com/silverstein-tickets/artist/887758', 'Co-headline with Story of the Year; tour closer'),
  ('story-of-the-year', '2026-12-13', NULL, 'House of Blues Boston', 'Boston', 'MA', 'USA', 'Camp Screamo 2 Tour', 'confirmed', NULL, 'Co-headline with Silverstein'),
  ('underoath', '2026-12-13', NULL, 'Coca-Cola Roxy', 'Atlanta', 'GA', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('northlane', '2026-12-15', NULL, 'Lucerna Music Bar', 'Prague', NULL, 'Czech Republic', NULL, 'confirmed', NULL, 'With Dayseeker and Siamese'),
  ('underoath', '2026-12-15', NULL, 'Austin City Limits Live', 'Austin', 'TX', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('northlane', '2026-12-16', NULL, 'Tonhalle - Kultfabrik', 'Munich', NULL, 'Germany', NULL, 'confirmed', 'https://www.ticketmaster.com/northlane-tickets/artist/1877916', 'With Dayseeker and Siamese'),
  ('underoath', '2026-12-16', NULL, 'Bayou Music Center', 'Houston', 'TX', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu'),
  ('underoath', '2026-12-18', NULL, 'Yuengling Center', 'Tampa', 'FL', 'USA', 'Define the Great Line 20th Anniversary Tour', 'confirmed', NULL, 'With August Burns Red and Atreyu');
